# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Qpsmtpd-Plugin-Quarantine
version:      1.02
version_from: lib/Qpsmtpd/Plugin/Quarantine.pm
installdirs:  site
requires:
    CGI:                           0
    DB_File:                       0
    Digest::MD5:                   0
    File::Slurp:                   0
    IO::Handle:                    0
    Mail::Address:                 0
    Mail::Field:                   0
    Mail::Field::Received:         0
    Mail::SendVarious:             0
    Mail::SPF::Query:              0
    Net::Netmask:                  0
    Net::SMTP:                     0
    OOPS:                          0.2001
    Qpsmtpd:                       0.32
    Sys::Hostname:                 0
    Template:                      0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
